### ISSUE TITLE
Remove mcare claims with no elig info from all analytic claim tables

### ISSUE THREAD

**Issue by elikern-kc** [PHSKC-APDE/claims_data#45]
Can verify by having to be found in final.xwalk_apde_mcaid_mcare_pha table

**Comment by alastairmatheson** [comment]
@dcolombara Is this implemented now?

**Comment by dcolombara** [comment]
**@alastairmatheson** & **@preason66** 

Theoretically, final.xwalk_apde_mcaid_mcare_pha may have some mcare members who lack elig data. This could happen when we have just their Mcare ID and SSN (**[PHClaims].[load_raw].[mcare_xwalk_bene_ssn]**) or just their Mcare ID & full name (**[PHClaims].[load_raw].[mcare_xwalk_edb_user_view]**), but they don't appear in the MBSF files. 

Do you want these people removed from final.xwalk_apde_mcaid_mcare_pha and all subsequent eligibility tables?

**Comment by alastairmatheson** [comment]
I think that's OK (though maybe a problem, see below). The issue here is claims that belong to people with no elig info should be removed from claim tables. The original idea was to restrict claims data to only those who are in the final.xwalk_apde_mcaid_mcare_pha table. Given what you say, this might not work and instead we should restrict to people in the final.mcaid_mcare_elig_demo table.

**Comment by dcolombara** [comment]
That's correct. The final.mcaid_mcare_elig_demo table is your best bet if you want to restrict to people with actual eligibility data.
